### PR TITLE
feat: add partial result event

### PR DESCRIPTION
**Pull request by riderx**
as reported here : https://github.com/capacitor-community/speech-recognition/issues/18
Partial result are missing.
Following the documentation here : https://capacitorjs.com/docs/plugins/android#plugin-events

I have add event for partial results.
I need to do more test, it's still wip

### CODE REVIEW

**Comment by riderx** [comment]
I did publish my fix as temporary module there : https://www.npmjs.com/package/@forgr/speech-recognition

**Comment by silviokuehn** [comment]
Not working for me. In iOS the result is always undefined and in Android the compiling of the code fails.

`node_modules/@forgr/speech-recognition/android/src/main/java/com/getcapacitor/community/speechrecognition/SpeechRecognition.java:282: error: ';' expected
                call.resolve()
                              ^`

**Comment by riderx** [comment]
@silviokuehn thanks for the report, 
I didn't check much in Android, i will fix this.
For iOS it works in my app, can you share your js code here?

**Comment by silviokuehn** [comment]
I used it the same way I use the original '@capacitor-community/speech-recognition' v.2.0.0. Tried on an iPhone 13 mini with iOS 15.x.

```
    NativeSpeechRecognition.start({
      language: navigator.language,
      maxResults: 1,
      partialResults: false,
      popup: false,
    }).then(result => {
      // And here result was undefined.
      if (result.matches.length > 0) {
        const currentMatch = result.matches[0] as string;
        this.onReceivedSpeechInput(currentMatch);
      }
    });
    ```

**Comment by riderx** [comment]
@silviokuehn android issue fixed and published.
For IOS are you free to show me, i cannot reproduce

**Comment by silviokuehn** [comment]
Still there in iOS. When you run the app the first time, it works. Since the 2nd run, the following logs appear.

```
To Native ->  SpeechRecognition available 50750415
⚡️  TO JS {"available":true}
⚡️  To Native ->  SpeechRecognition hasPermission 50750416
2022-01-17 16:03:26.254036+0100 App[21555:278741] [plugin] AddInstanceForFactory: No factory registered for id <CFUUID 0x6000019209a0> F8BB1C28-BAE8-11D6-9C31-00039315CD46
⚡️  TO JS {"permission":true}
⚡️  To Native ->  SpeechRecognition start 50750417
⚡️  TO JS undefined
⚡️  [log] - undefined
```

The official version 2.0.0 has not that problem. Anyway - there are other differences between the platforms. Android has an "auto stop" even in mode `partialResults: false` when the user is finished e.g. with speaking a location address into the the device. iOS does not auto stop. For me a 5-second-timer in iOS is the workaround for that.

**Comment by riderx** [comment]
Ok thanks that more precise, I will have look tomorrow

**Comment by stewones** [comment]
hey hey

Thank you @riderx for the PR

Tested on iOS and works fine. having issues with Android but I doubt it has something to do with your changes.

I'm going to merge this one, since the original purpose was already reached.

**Comment by riderx** [comment]
thanks !

**Pull request merged**
